[package]
name = "pkweb"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
#url = "2.5.0"
warp = { version = "0.3",  features = ["multer", "multipart", "tokio-tungstenite","websocket", "tls", "tokio-rustls"] }
percent-encoding = "2.3.1"
pkcore = { git = "https://github.com/ImperialBower/pkcore.git", tag = "v0.0.12" }
serde_derive = "1.0.195"
pretty_env_logger = "0.5.0"
serde = "1.0.197"
